### ISSUE TITLE
Iteration through files is asynchronous but not awaited

### ISSUE THREAD

**Issue by atkinchris** [JasonAtallah/express-directory-router#1]
The function called for each iteration through discovered files to creates routes is asynchronous, but it's not awaited. The could lead to the control flow being returned to the Express server creation before routes are complete.

https://github.com/JasonAtallah/express-directory-router/blob/e0048cc6499f328ffac1c9597b9d122f8eff32bf/src/index.ts#L44

**Comment by JasonAtallah** [comment]
Good catch, I updated the loop. Thanks!
