### ISSUE TITLE
Compiled files include generator boilerplate

### ISSUE THREAD

**Issue by atkinchris** [JasonAtallah/express-directory-router#2]
The build at the moment targets `ES5`. As this is a library targeting Node, it could be targeted to a more modern feature set and avoid including generator boilerplate (and pre-ES6 style code).

https://github.com/JasonAtallah/express-directory-router/blob/e0048cc6499f328ffac1c9597b9d122f8eff32bf/tsconfig.json#L3

Base `tsconfig` files for each Node version can be installed from https://github.com/tsconfig/bases. Targeting the current maintenance LTS or above (Node 12 - https://www.npmjs.com/package/@tsconfig/node12) cuts compiled size by a half and avoids the generator boilerplate.

```sh
npm install -D @tsconfig/node12
```

```json
// tsconfig.json
{
  "extends": "@tsconfig/node12",
  "compilerOptions": {
    "declaration": true,
    "outDir": "./lib"
  },
  "include": ["src"],
  "exclude": ["node_modules", "tests"]
}
```

**Comment by JasonAtallah** [comment]
That's true, I don't care much to support anything below v12.

tsconfig updated
